# Generated by Django 4.1.4 on 2022-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='currency code', max_length=3)),
                ('language', models.CharField(help_text='language', max_length=20)),
                ('target_currency_code', models.CharField(help_text='target currency code', max_length=3)),
            ],
            options={
                'db_table': 'currency_pair',
            },
        ),
    ]
